version: '3'

# to setup the network, run `docker network create proxynet`
networks:
  default:
    external:
      name: proxynet

services:
  proxy:
    image: casmacc/nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./volumes/html:/usr/share/nginx/html
      # - ./volumes/certs:/etc/nginx/certs
      # - ./volumes/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
  base:
    image: casmacc/html_helloworld
    ports:
      - "3090:80"
    environment:
      VIRTUAL_HOST: myhost.com
  h1:
    image: casmacc/sinatra_helloworld
    ports:
      - "3095:3090"
    environment:
      VIRTUAL_HOST: h1.myhost.com
  s1:
    image: casmacc/sinatra_helloworld
    ports:
      - "4090:3090"
    environment:
      VIRTUAL_HOST: s1.myhost.com
  s2:
    image: casmacc/sinatra_helloworld
    ports:
      - "4091:3090"
    environment:
      VIRTUAL_HOST: s2.myhost.com
  p1:
    image: casmacc/phoenix_helloworld
    ports:
      - "5000:4000"
    environment:
      VIRTUAL_HOST: p1.myhost.com
  p2:
    image: casmacc/phoenix_helloworld
    ports:
      - "5001:4000"
    environment:
      VIRTUAL_HOST: p2.myhost.com
  whoami:
    image: jwilder/whoami
    ports:
      - "8000:8000"
    environment:
      VIRTUAL_HOST: whoami.myhost.com
