version: '3'

# to setup the network, run `docker network create proxynet`
networks:
  default:
    external:
      name: proxynet

services:
  proxy:
    image: casmacc/nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./volumes/certs:/etc/nginx/certs
      - ./volumes/certs:/etc/nginx/certs
      - ./volumes/conf.d:/etc/nginx/conf.d
      - ./volumes/vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
  base:
    image: casmacc/html_helloworld
    volumes:
      - ./volumes/html:/usr/share/nginx/html
    ports:
      - "3090:80"
    environment:
      VIRTUAL_HOST: ${NHOST}
  h1:
    image: casmacc/html_helloworld
    ports:
      - "3091:80"
    environment:
      VIRTUAL_HOST: h1.${NHOST}
  s1:
    image: casmacc/sinatra_helloworld
    ports:
      - "4090:3090"
    environment:
      VIRTUAL_HOST: s1.${NHOST}
